# [[file:bevy.note::e345323a][e345323a]]
[package]
name = "bevy_game"
version = "0.1.1"
publish = false
authors = ["Wenping Guo <ybyygu@gmail.com>"]
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[features]
dev = ["bevy/bevy_dylib"]

# Bevy defaults minus audio and some other not needed things
# see https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L31-L54
default = [
  "bevy/animation",
  "bevy/bevy_asset",
  "bevy/bevy_scene",
  "bevy/bevy_winit",
  "bevy/bevy_core_pipeline",
  "bevy/bevy_pbr",
  "bevy/bevy_gltf",
  "bevy/bevy_render",
  "bevy/bevy_sprite",
  "bevy/bevy_text",
  "bevy/bevy_ui",
  "bevy/png",
  "bevy/hdr",
  "bevy/zstd",
  "bevy/x11",
  "bevy/ktx2",
  "bevy/filesystem_watcher",
  "bevy/tonemapping_luts",
]

[dependencies]
bevy = { version = "0.10", default-features = false }
bevy_kira_audio = { version = "0.15" }
bevy_asset_loader = { version = "0.15" }
rand = { version = "0.8.3" }
bevy-inspector-egui = "0.18.0"
bevy_mod_picking = "0.12.0"
bevy_mod_raycast = "0.8.0"
bevy_egui = "0.20"
smooth-bevy-cameras = "0.8.0"
gut = { version = "0.4.3", package = "gchemol-gut" }
gchemol-core = { version="0.1.4", features=["adhoc"] }
# text_parser = { version = "0.4.5", package = "gchemol-parser" }
# wasm build panic issue: https://bevy-cheatbook.github.io/platforms/wasm/panic-console.html
console_error_panic_hook = "0.1"
# mendeleev = { version = "0.7", features = ["color"]}
bevy_prototype_debug_lines = { version = "0.10.1", features = ["3d"] }
bevy_panorbit_camera = "0.1.1"

# keep the following in sync with Bevy's dependencies
winit = { version = "0.28", default-features = false }
image = { version = "0.24", default-features = false }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4", features = ["derive"] }
gchemol = { version = "0.1.3", features=["adhoc"] }

[build-dependencies]
embed-resource = "1.4"

[workspace]

[patch.crates-io]
gchemol-gut = { path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gut" }
gchemol-core = { path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gchemol-core" }
# e345323a ends here
